kill-switch now changes the value in a safer manner

diff --git a/mullvad b/mullvad
--- a/mullvad
+++ b/mullvad
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #script that makes it easier to use WireGuard with Mullvad
 
 #Error function	
@@ -8,9 +7,31 @@ error() {
 	exit 1
 }
 
+kill_switch_verify(){
+    local ANS
+	echo -n "You are trying to change the kill-switch value of a server you're currently connected to. "
+	echo "This requires disconnecting from the server before doing."
+	echo 
+	echo -n "The program will automatically reconnect you to the same server if you choose to proceed with the operation, "
+	echo "but will leave you unprotected and potentially vurnable for a very brief moment. This is not recommended."
+	echo
+	echo -n "Do you wish to continue? [y/N] "
+
+	while : 
+	do
+    read ANS
+	if [[ $ANS =~ ^y$|^Y$ ]]; then
+        USR_OPT="y"; return
+	elif [[ $ANS =~ ^n$|^N$ ]]; then
+        USR_OPT=$ANS; return
+    else 
+		echo -n "Invalid input, please try again [y/N] "
+    fi
+	done
+}
+
 kill_switch(){
 	local PostUp PreDown
-
 	echo "Turning $1 kill-switch"
 	echo "-----------------------"
 
@@ -22,12 +43,25 @@ kill_switch(){
 	PreDown="PreDown = $PreDown"	
 	
 	servers=$(egrep -o "^[^:]+" /etc/wireguard/*servers.txt 2>/dev/null)
-	#Resets the argument all to all the servers
-	if [[ $2 == all ]]; then set "$1" "$servers"; fi
+	#Resets the argument "$all" to all the servers
+	if [[ $2 == all ]]; then set "$1" "$servers"; fi	
 
-	#For every input, always remove the kill-switch
 	for arg in ${@:2} ; do
+		#Check if valid syntax
+		[[ "$arg" =~ ^([a-z]{2}[0-9]{1,2})$ ]] || (echo "Error: invalid input $arg." && continue)
+
+		#Security check, see kill_switch_verify function above
+		if [[ "${CURR_CONNECTION//*-}" = "$arg" ]]; then
+			kill_switch_verify
+			if [[ "$USR_OPT" == "y" ]]; then
+				sudo wg-quick down "$CURR_CONNECTION"  &>/dev/null 
+			else
+				continue
+			fi
+		fi
+
 		if grep -q "$arg" <<< "$servers"; then
+			#always remove the kill-switch
 			sourceFile="/etc/wireguard/mullvad-$arg.conf"
 			umask 077
 			sudo grep -v "REJECT" "$sourceFile" > "/tmp/$arg.tmp"
@@ -41,7 +75,11 @@ kill_switch(){
 		else
 			echo "Error: $arg is not a valid server."
 		fi
-done 
+	done 
+
+	#Enables server again (optional), see above	
+	if [[ "$USR_OPT" == "y" ]]; then sudo wg-quick up "$CURR_CONNECTION" &>/dev/null; fi
+
 	echo "Done!"
 }
 
@@ -115,13 +153,6 @@ main() {
 			main list
 			;;
 
-		verify )
-			MYIP=$(curl -s https://api.ipify.org)
-			TARGETIP=$(curl -s https://am.i.mullvad.net)
-
-			[[ "$MYIP" == "$TARGETIP" ]] 1> "Verified!" || error "NO"
-		;;
-
 		list|ls|l )
 			echo "Available servers"
 			echo "-----------------------"
@@ -132,9 +163,9 @@ main() {
 	  		echo "Usage: $(basename "$0") <cmd> [<server>]" >&2
 	  		echo
 	  		echo -e "  connect \t\t\t Connects to the first Swedish server."
-	 		echo -e "  connect [<server>]\t Connects to a specified servers."
+	 		echo -e "  connect [<server>]\t\t Connects to a specified servers."
 	  		echo -e "  disconnect\t\t\t Disconnects from the active server."
-	  		echo -e "  kill-switch-{on|off}\t Changes the kill-switch value of specified server(s)."
+	  		echo -e "  kill-switch-{on|off}\t\t Changes the kill-switch value of specified server(s)."
 	 		echo -e "  list\t\t\t\t List available servers."
 	  		echo -e "  status\t\t\t Show current status of connection."
 	  		echo -e "  update\t\t\t Updates the server list."
