Start-up is now fully functional
Signed-off-by: Adi Hrustic <hrustic@student.chalmers.se>

diff --git a/mullvad b/mullvad
--- a/mullvad
+++ b/mullvad
@@ -11,22 +11,29 @@ error() {
 }
 
 startup() {
-	local CURR_STARTUP TARGET CONFIG
-	CONFIG=$1                                             # On or off
-	TARGET=$2                                             # Target autostart, if any.
-	CURR_STARTUP=$(cat $HOME/.config/mullvad/start-up.txt 2>/dev/null) #get current autostart
-	if [[ $CONFIG == "on" ]]; then
-		#Can't have multiple
-		[[ -z "$CURR_STARTUP" ]] || error "Start up server already set to $CURR_STARTUP."
+	local TARGET OPTION START_UP ENABLED
+	OPTION=$1
+	TARGET=$2
+	#Checks to see if we already have a start-up server enabled
+	#If so, ENABLED will be set to 'enabled' and break the loop
+	for START_UP in ${AVAILABLE_SERVERS}; do
+		ENABLED=$(systemctl is-enabled wg-quick@mullvad-$START_UP)
+		[[ $ENABLED == disabled ]] || break
+	done
+
+	if [[ $OPTION == "on" ]]; then
+		[[ $ENABLED != enabled ]] || error "Start-up server already set to: $START_UP"
 		sudo systemctl enable wg-quick@mullvad-"$TARGET" &>/dev/null
-		echo $TARGET > $HOME/.config/mullvad/start-up.txt
-	elif [[ $CONFIG == "off" ]]; then
-		[[ $CURR_STARTUP ]] || error "No autostart is active."
-		sudo systemctl disable wg-quick@"$CURR_CONNECTION" &>/dev/null
-		echo "" > $HOME/.config/mullvad/start-up.txt
-	elif [[ $CONFIG == "show" ]]; then
-		echo -e "${GREEN}Current start-up is set to: $CURR_STARTUP${NC}"
+
+	elif [[ $OPTION == "off" ]]; then
+		[[ $ENABLED == enabled ]] || error "No start-up server is set."
+		sudo systemctl disable wg-quick@mullvad-"$START_UP" &>/dev/null
+
+	elif [[ $OPTION == "show" ]]; then
+		[[ $ENABLED == enabled ]] || START_UP=EMPTY
+		echo -e "${GREEN}Current start-up is set to: ${START_UP}${NC}"
 		exit 0
+
 	else
 		error "Bad input."
 	fi
@@ -34,32 +41,31 @@ startup() {
 }
 
 verify_connection() {
+	local TARGET
 	echo -e "# Verifying connection #"
 	TARGET=$(curl -s https://am.i.mullvad.net/json | jq -r .mullvad_exit_ip_hostname)
-	[[ "${TARGET//-*/}" == "${CURR_CONNECTION//*-/}" ]] || error "NOT able to verify!"
+	[[ "${TARGET//-*/}" == "${CURRENT_CONNECTION//*-/}" ]] || error "NOT able to verify!"
 	echo -e "${GREEN}Connection verified!${NC}"
 }
 
 update_default() {
+	echo -e "# Updating default server #"
 	local ANS
 	echo -n "Please select the name of your default server (e.g. se1): "
-
 	while :; do
 		read ANS
 		[[ ! $ANS =~ ^$ ]] && break
 		echo -en "\nInvalid input, please try again: "
 	done
-
 	echo $ANS >$HOME/.config/mullvad/default.txt
-	DEFAULT=$ANS
+	DEFAULT_SERVER=$ANS
 	echo -e "${GREEN}Default set to $ANS!${NC}"
 }
 
 server_change() {
 	local ANS
-	echo -e "${RED}Error: you're currently connected to ${CURR_CONNECTION//*-/}.${NC}"
-	echo -n "Do you wish to change to ${SERVER//*-/}? [Y/n] "
-
+	echo -e "${RED}Error: you're currently connected to ${CURRENT_CONNECTION//*-/}.${NC}"
+	echo -n "Do you wish to change to ${TARGET_SERVER//*-/}? [Y/n] "
 	while :; do
 		read ANS
 		[[ $ANS =~ ^(y|Y|^$)$ ]] && $0 disconnect &>/dev/null && break
@@ -76,7 +82,6 @@ kill_switch_verify() {
 	echo "This requires disconnecting from the server before proceeding."
 	echo
 	echo -n "Do you wish to continue? [Y/n] "
-
 	while :; do
 		read ANS
 		[[ $ANS =~ ^(y|Y|^$)$ ]] && KS_YES=true && break
@@ -88,28 +93,24 @@ kill_switch_verify() {
 kill_switch() {
 	local PostUp PreDown
 	echo -e "# Turning $1 kill-switch #"
-
 	PostUp="iptables -I OUTPUT ! -o %i -m mark ! --mark \$(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT"
 	PostUp=${PostUp/*/"PostUp = $PostUp && ${PostUp//ip/ip6}"}
 	PreDown=${PostUp//-I/-D}
 	PreDown=${PreDown//PostUp/PreDown}
-
-	servers=$(awk -F'[:]' '{print $1" "}' $HOME/.config/mullvad/*servers.txt 2>/dev/null)
-	#Resets the argument "$all" to all the servers
-	[[ $2 == all ]] && set "$1" "$servers"
-
-	for ARG in ${*:2}; do
+	#If all servers were specified, we change to this value
+	[[ $2 == all ]] && set "$1" "$AVAILABLE_SERVERS"
+	for ARG in ${2}; do
 		#Check if valid syntax
 		[[ ! $ARG =~ ^([a-z]{2}[0-9]{1,2})$ ]] && echo -e "${RED}Error: invalid input $ARG.${NC}" && continue
 
 		#Security check, see kill_switch_verify function above
-		if [[ "${CURR_CONNECTION//*-/}" == "$ARG" ]]; then
+		if [[ "${CURRENT_CONNECTION//*-/}" == "$ARG" ]]; then
 			kill_switch_verify
 			[[ $KS_YES ]] || continue
 			"$0" disconnect &>/dev/null
 		fi
 
-		if grep -q "$ARG" <<<"$servers"; then
+		if grep -q "$ARG" <<<"$AVAILABLE_SERVERS"; then
 			#always remove the kill-switch
 			sourceFile="/etc/wireguard/mullvad-$ARG.conf"
 			umask 077
@@ -127,70 +128,69 @@ kill_switch() {
 	[[ ! $KS_YES ]] && echo -e "${GREEN}Done.${NC}" && exit 1
 	#Enables and verifies connection again (optional), see above
 	echo "# Reconnecting #"
-	"$0" connect "${CURR_CONNECTION//*-/}" &>/dev/null && "$0" verify
+	"$0" connect "${CURRENT_CONNECTION//*-/}" &>/dev/null && "$0" verify
 }
 
-#The syntax ${2:-DEFAULT} expands to default server if $2 is unset or is set to the empty string.
-CMD=$1
-DEFAULT=$(cat $HOME/.config/mullvad/default.txt 2>/dev/null)
-[[ -z "$DEFAULT" ]] && echo -e "${RED}Error: Default server needs to be set.${NC}" && update_default
-SERVER=mullvad-${2:-$DEFAULT}
-CURR_CONNECTION=$(wg show interfaces)
-case $CMD in
+#The syntax ${2:-DEFAULT_SERVER} expands to default server if $2 is unset or is set to the empty string.
+#If no default server has been set, the user will be prompted to choose one.
+COMMAND=$1
+DEFAULT_SERVER=$(cat $HOME/.config/mullvad/default.txt 2>/dev/null)
+[[ -z "$DEFAULT_SERVER" ]] && echo -e "${RED}Error: Default server needs to be set.${NC}" && update_default
+TARGET_SERVER=mullvad-${2:-$DEFAULT_SERVER}
+CURRENT_CONNECTION=$(wg show interfaces)
+AVAILABLE_SERVERS=$(awk -F'[:]' '{print $1" "}' $HOME/.config/mullvad/*servers.txt 2>/dev/null)
+
+case $COMMAND in
 connect)
-	echo -e "# Connecting to ${SERVER//*-/} #"
-	#Check is already connecteed
-	[[ $CURR_CONNECTION != $SERVER ]] || error "already connected to ${SERVER//*-/}."
-
-	#If above try, ask if change
-	[[ ! $CURR_CONNECTION ]] || server_change
-
-	#Try to connect to chosen server, else throw error.
-	sudo wg-quick up "$SERVER" &>/dev/null || error "server does not exist, disconnecting."
-
+	echo -e "# Connecting to ${TARGET_SERVER//*-/} #"
+	[[ $CURRENT_CONNECTION != $TARGET_SERVER ]] || error "already connected to ${TARGET_SERVER//*-/}."
+	[[ ! $CURRENT_CONNECTION ]] || server_change
+	sudo wg-quick up "$TARGET_SERVER" &>/dev/null || error "server does not exist, disconnecting."
 	echo -e "${GREEN}Connected!${NC}"
-	CURR_CONNECTION=$SERVER
+	#Verifies connection, always done
+	CURRENT_CONNECTION=$TARGET_SERVER
 	verify_connection
 	;;
 
 disconnect)
 	echo -e "# Disconnecting VPN #"
-	sudo wg-quick down "$CURR_CONNECTION" &>/dev/null || error "not connected."
+	sudo wg-quick down "$CURRENT_CONNECTION" &>/dev/null || error "not connected."
 	echo -e "${GREEN}Disconnected${NC}"
 	;;
 
 kill-switch)
-	SERVER=${3:-$DEFAULT}
+	TARGET_SERVER=${3:-$DEFAULT_SERVER}
 	[[ $2 =~ on|off ]] || error "Invalid choice, aborting."
-	kill_switch "$2" "$SERVER"
+	kill_switch "$2" "$TARGET_SERVER"
 	;;
 
 list | ls | l)
-	echo "Available servers"
-	echo "-----------------------"
+	#Option to view current default server
+	if [[ $2 == default ]]; then
+		echo -e "${GREEN}Default server is set to: $DEFAULT_SERVER${NC}"
+		exit 0
+	fi 
+	echo "# Available servers #"
+	echo "---------------------"
 	echo -e "$(cat $HOME/.config/mullvad/*servers.txt)" || error "no server list found. Try updating."
 	;;
 
 start-up)
-	SERVER=${3:-$DEFAULT}
-	[[ $(grep "$SERVER" $HOME/.config/mullvad/*servers.txt) ]] || error "Invalid server, aborting."
-	startup "$2" "$SERVER"
-	;;	
+	TARGET_SERVER=${3:-$DEFAULT_SERVER}
+	[[ $(grep "$TARGET_SERVER" <<< "$AVAILABLE_SERVERS") ]] || error "Invalid server, aborting."
+	startup "$2" "$TARGET_SERVER"
+	;;
 
 status)
-	[[ $CURR_CONNECTION ]] || error "not connected."
+	[[ $CURRENT_CONNECTION ]] || error "not connected."
 	sudo wg
 	;;
 
 update)
-	#If want to update default, do it.
 	if [[ $2 == "default" ]]; then
 		update_default
-		exit 1
 
-		#Else if want to update the whole list
 	elif [[ $2 == "servers" ]]; then
-
 		echo -e "# Fetching server list #"
 		curl -sLO https://mullvad.net/media/files/mullvad-wg.sh
 		chmod +x ./mullvad-wg.sh
@@ -213,13 +213,14 @@ update)
 		mv /tmp/mullvad_servers.txt $HOME/.config/mullvad/
 		rm ./mullvad-wg.sh
 		"$0" list
+
 	else
 		error "unknown command, use '$(basename "$0") help' for help."
 	fi
 	;;
 
 verify)
-	[[ $CURR_CONNECTION ]] || error "not connected."
+	[[ $CURRENT_CONNECTION ]] || error "not connected."
 	verify_connection
 	;;
 
@@ -229,12 +230,13 @@ help | -h)
 	echo -e "  connect \t\t\t Connects to the default server."
 	echo -e "  connect <server>\t\t Connects to a specified servers."
 	echo -e "  disconnect\t\t\t Disconnects from the active server."
-	echo -e "  kill-switch-{on|off}\t\t Changes the kill-switch value of specified server(s)."
+	echo -e "  kill-switch <on|off> <server(s)>\t\t Changes the kill-switch value of specified server(s)."
 	echo -e "  list\t\t\t\t List available servers."
 	echo -e "  status\t\t\t Show current status of connection."
+	echo -e "  start-up <on|off> <server>\t\t\t Configures active server on system start-up."
 	echo -e "  update default\t\t Sets a new default server."
 	echo -e "  update servers\t\t Updates the server list."
-	echo -e "  verify\t\t\t Verify if you're connected to Mullvad."
+	echo -e "  verify\t\t\t Verify your connection."
 	echo
 	echo -e "  help\t\t\t\t Brings up this help menu."
 	echo
@@ -244,3 +246,4 @@ help | -h)
 	error "unknown command, use '$(basename "$0") help' for help."
 	;;
 esac
+exit 0
